rm -f ./config/buildinfo.go
cat <<EOT >> ./config/buildinfo.go
package config

/*
This file is automatically generated by ToDD build scripts.
Please do not edit.
*/

var (
	BuildInfo = map[string]string{
		"buildSha": "$(git rev-parse HEAD)",
	}
)

EOT
